# Generated by Django 4.2 on 2023-04-14 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(blank=True, max_length=200, null=True)),
                ('date_debut', models.DateTimeField(blank=True, null=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('temps', models.CharField(blank=True, choices=[('UNE SEMAINE', 'UNE SEMAINE'), ('UN MOIS', 'UN MOIS'), ('DEUX MOIS', 'DEUX MOIS'), ('TROIS MOIS', 'TROIS MOIS')], max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='./image/'),
        ),
    ]
