# Generated by Django 4.2 on 2023-04-14 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accueil', '0002_service_client_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='destination',
            new_name='nom_service',
        ),
        migrations.RemoveField(
            model_name='service',
            name='date_debut',
        ),
        migrations.RemoveField(
            model_name='service',
            name='date_fin',
        ),
        migrations.RemoveField(
            model_name='service',
            name='temps',
        ),
        migrations.CreateModel(
            name='Appartenir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(blank=True, max_length=200, null=True)),
                ('date_debut', models.DateTimeField(blank=True, null=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('save_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accueil.service')),
            ],
        ),
    ]
