# Generated by Django 4.2 on 2023-04-15 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0003_rename_destination_service_nom_service_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='image',
        ),
        migrations.AddField(
            model_name='client',
            name='contact',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='date_expiration_passeport',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='dnaiss',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='nationalite',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='numero_passeport',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='./image/'),
        ),
        migrations.AddField(
            model_name='client',
            name='residence',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='sexe',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
