# Generated by Django 4.2 on 2023-04-15 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0005_client_save_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='nom_service',
        ),
        migrations.AddField(
            model_name='service',
            name='libelle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='montant',
            field=models.FloatField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='nombre_jours',
            field=models.IntegerField(blank=True, max_length=200, null=True),
        ),
    ]
