# Generated by Django 4.2 on 2023-04-15 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0006_remove_service_nom_service_service_libelle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appartenir',
            name='date_fin',
        ),
        migrations.AddField(
            model_name='appartenir',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accueil.client'),
        ),
        migrations.AddField(
            model_name='appartenir',
            name='date_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appartenir',
            name='quantite',
            field=models.IntegerField(blank=True, max_length=200, null=True),
        ),
    ]
