# Generated by Django 4.2 on 2023-04-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0007_remove_appartenir_date_fin_appartenir_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appartenir',
            name='total_unitaire',
            field=models.FloatField(blank=True, max_length=200, null=True),
        ),
    ]
