# Generated by Django 4.2 on 2023-04-15 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0008_appartenir_total_unitaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appartenir',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
